### ISSUE TITLE
New truck Fueler job

### ISSUE THREAD

**Issue by KonnanGaming** [FlawwsX/GTRoleplay#11]
Can we get a new truck for the fueler job? 
https://www.gta5-mods.com/vehicles/2016-kenworth-t680-semi-truck
or
https://www.gta5-mods.com/vehicles/2014-kenworth-w900-6x2-mid-cab-livery-extras-add-on-replace-mrjappie241

**Comment by FlawwsX** [comment]
Rather than a new truck I will go ahead and test the 2 you have suggested, if they work good I will make sure to add them to the list where you get to choose your vehicle.
