### ISSUE TITLE
Adding more public jobs

### ISSUE THREAD

**Issue by FlawwsX** [FlawwsX/GTRoleplay#2]
**Describe your suggestion/feature request**
I would like to see more jobs added to the game. If I'm being in-depth I would say add some garbage truck jobs, pool cleaner jobs, bank security jobs, etc... jobs which are much more fun than the regular boring jobs.

**Do you have additional information you can give us regarding this feature?**
I would say that they should definitely be interactive rather than sitting in a circle. In addition, this will add to the popularity of the server because people are really looking for servers that have a lot of jobs.

**Does anyone else want this feature?**
Flawws :P

**Comment by Plaza31** [comment]
Ok i'll get to that in a little

**Comment by FlawwsX** [comment]
Resolved by @Plaza31
