### ISSUE TITLE
Job Center

### ISSUE THREAD

**Issue by KonnanGaming** [FlawwsX/GTRoleplay#3]
Job center once again not working. No menu is brought up when I enter circle and press E.

**Comment by FlawwsX** [comment]
This seems to be a client sided issue since there are some people who can use it and some who can’t. I’ll look more into it to see why the menu isn’t coming up like every other menu. 

- Flawws

**Comment by voltrox910** [comment]
The issue is esx_joblistings keeps getting removed from .CFG file somehow I have replaced it 2 times. After I replace it or re ensure it the thing works.

-Volt-

**Comment by FlawwsX** [comment]
After talking to the authors of the script, it's a client-sided issue and cannot be resolved. 
I've tried something to fix it which you can test in-game.
