### ISSUE TITLE
Dealership cars list

### ISSUE THREAD

**Issue by KonnanGaming** [FlawwsX/GTRoleplay#4]
Would it possible for someone to put together a list of all the cars offered at each dealership? It would make car buying easier and dealers wouldn't have to pull out so many vehicles to show customers.

**Comment by FlawwsX** [comment]
We currently do have a list of vehicles for each dealership in a Google Sheets document. The only issue with that is, it eliminates the need for a Dealer then. You have no RP between you to discuss which cars there are and to ask for the name, specs, etc.... Once a player chooses to be a dealer, it is their responsibility to act as a dealer and get these cars out.

**Comment by KonnanGaming** [comment]
You would still have to go to the dealership. I think it would make things easier for those who aren't really sure what kind of car they want. They could look at the listing and then head to the dealership to check out the car maybe take it for a test drive.

**Comment by FlawwsX** [comment]
It might be possible to make something with the Tablet we have in game or do something on the phone where dealerships can list their available vehicles. I get what you mean, irl you look online first before going and then you have an idea of what you want to buy. My perspective as changed on this now that you put it this way. What do you think would be the best way to do it in game?

**Comment by KonnanGaming** [comment]
Easiest way would probably make a Discord channel and the dealers can put there stock which can be edited to add and/or remove vehicles.

**Comment by FlawwsX** [comment]
Yep, I’ll most likely add this. It’ll most likely be a feature for Season 2. I’ve got an image of what I want to do, thank you for the suggestion.
