### ISSUE TITLE
Personal vehicle locked doors

### ISSUE THREAD

**Issue by KonnanGaming** [FlawwsX/GTRoleplay#6]
When I lock my doors at a job site and get into a "work" vehicle, when I return to my vehicle I can not unlock my doors or get into my car.

**Comment by FlawwsX** [comment]
Did you use M menu to do this? If so, is there a way you can test this with /save and /lock?

**Comment by KonnanGaming** [comment]
I use the M menu to set my car and controller to lock usually. I will test this when I get a chance with /save and /lock.

**Comment by FlawwsX** [comment]
Appreciate it. The Development team is currently working on a new system for the vehicle locking.

**Comment by FlawwsX** [comment]
Appreciate it. The Development team is currently working on a new system for the vehicle locking.

**Comment by KonnanGaming** [comment]
/save and /lock didn't work. As soon as I get into the work vehicle and drive off it seems to break the locking of my car and it says I don't have a Saved vehicle.

**Comment by FlawwsX** [comment]
All right, thanks for testing. The development team has implemented a new locking system into the new season.
